forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs/stdlib",
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git'

mod "puppetlabs/mysql"
mod "puppetlabs/apt"

mod "pcfens/php_web",
  :git => 'https://github.com/pcfens/puppet-php_web.git',
  :ref => 'overhaul'
